In [1]:
# import the libraries
import numpy as np

In [2]:
# creating an array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
# checking the dimension of the array
a.ndim

1

In [4]:
# Creat a two Dimension array
b=np.array([[1,2,3,4,5],[2,3,4,8,9]])
b

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 8, 9]])

In [5]:
b.ndim

2

In [6]:
# Creating three dimesion array
c=np.array([[[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]]])
c

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]])

In [7]:
c.ndim

3

# Zeros and Ones

In [8]:
var=np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
var1=np.ones(10)
var1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
var2=np.ones((3,4,5))
var2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [11]:
var3=np.zeros((3,2,3))

In [12]:
var3

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
var4=np.zeros((4,2,3))

In [14]:
var4

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# Functions in Numpy

In [15]:
var=np.array([20,30,40,50,70,60])
var

array([20, 30, 40, 50, 70, 60])

In [16]:
var.ndim

1

In [17]:
type(var)

numpy.ndarray

In [18]:
#argmax=index postion with max value
var.argmax()

4

In [19]:
#argmin=index position with min value
var.argmin()

0

In [20]:
var[0]

20

In [21]:
var[2]

40

In [22]:
var[1]

30

In [23]:
var

array([20, 30, 40, 50, 70, 60])

In [24]:
var[0:2]

array([20, 30])

In [25]:
var[1:5]

array([30, 40, 50, 70])

In [26]:
var[:-1]

array([20, 30, 40, 50, 70])

In [27]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr1=np.array([1,2.4,3,5,6])
arr1

array([1. , 2.4, 3. , 5. , 6. ])

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr1.size

5

In [32]:
# Create a two dimension array
# four array in external array
# it should have two elements in each

In [33]:
arr=np.array([[1,2],[2,3],[3,4],[4,5]])
arr

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [34]:
arr.dtype

dtype('int32')

In [35]:
arr.size

8

In [36]:
arr.ndim

2

In [37]:
my_matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [38]:
b=np.array(my_matrix)

In [39]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
b.dtype

dtype('int32')

In [41]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [44]:
a=np.arange(10)

In [45]:
a.ndim

1

In [46]:
#Reshape

In [47]:
a=np.arange(12)

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
np.arange(12).reshape(4,3)             #1,12  2,6  3,4   4,3  6,2   12,1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
np.arange(12).reshape(3,4)             #1,12  2,6  3,4   4,3  6,2   12,1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a=np.arange(12).reshape(6,2)  
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [52]:
a.shape

(6, 2)

In [53]:
a.max()

11

In [54]:
b=np.arange(12).reshape(2,2,3)

In [55]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [56]:
b=np.arange(12).reshape(1,6,2)

In [57]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [67]:
b.ndim

3

In [58]:
x=[1,4,5,28]
x

[1, 4, 5, 28]

In [59]:
np.sqrt(x)

array([1.        , 2.        , 2.23606798, 5.29150262])

In [60]:
np.log(x)

array([0.        , 1.38629436, 1.60943791, 3.33220451])

In [61]:
np.exp(x)

array([2.71828183e+00, 5.45981500e+01, 1.48413159e+02, 1.44625706e+12])

In [62]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [63]:
#transpose
a1=a.T

In [64]:
a1

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

# Floor and Ceil

In [65]:
arr1=np.array([10.8,3.64,6.6,10.2])
arr1

array([10.8 ,  3.64,  6.6 , 10.2 ])

In [66]:
np.floor(arr1)

array([10.,  3.,  6., 10.])

In [67]:
np.ceil(arr1)

array([11.,  4.,  7., 11.])

In [68]:
round_data=np.round(arr1)

In [69]:
round_data

array([11.,  4.,  7., 10.])

In [70]:
np.round(3.5)

4.0

In [71]:
np.round(3.4)

3.0

# Stacking

In [76]:
# Vertical Stacking- No of Columns Should be same
# Horizonatl Stacking- No of rows  should be same

In [73]:
arr1=np.arange(10).reshape(2,5)
arr2=np.arange(20).reshape(4,5)

In [74]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [78]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
np.vstack((arr2,arr1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [80]:
np.hstack((arr1,arr2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [81]:
arr3=np.arange(24).reshape(4,6)

In [82]:
np.hstack((arr3,arr2))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10, 11,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 10, 11, 12, 13, 14],
       [18, 19, 20, 21, 22, 23, 15, 16, 17, 18, 19]])

# Split

In [83]:
# Vertical Split- Splits an array into multiple array vertically (Row Wise)
# Horizontal Split- Splits an array into multiple array horizontally (Column Wise)

In [84]:
arr2=np.arange(100).reshape(10,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [94]:
np.vsplit(arr2,5)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]),
 array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [96]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
np.hsplit(arr2,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [97]:
np.hsplit(arr2,5)

[array([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41],
        [50, 51],
        [60, 61],
        [70, 71],
        [80, 81],
        [90, 91]]),
 array([[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43],
        [52, 53],
        [62, 63],
        [72, 73],
        [82, 83],
        [92, 93]]),
 array([[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45],
        [54, 55],
        [64, 65],
        [74, 75],
        [84, 85],
        [94, 95]]),
 array([[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47],
        [56, 57],
        [66, 67],
        [76, 77],
        [86, 87],
        [96, 97]]),
 array([[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49],
        [58, 59],
        [68, 69],
        [78, 79],
        [88, 89],
        [98, 99]])]

# Linspace

In [103]:
# returns evenly spaced numbers over specified interval


In [104]:
np.linspace(0,30)  # start # end (Here end is included), and default it gives 50 elements

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

In [105]:
np.linspace(0,25,100)

array([ 0.        ,  0.25252525,  0.50505051,  0.75757576,  1.01010101,
        1.26262626,  1.51515152,  1.76767677,  2.02020202,  2.27272727,
        2.52525253,  2.77777778,  3.03030303,  3.28282828,  3.53535354,
        3.78787879,  4.04040404,  4.29292929,  4.54545455,  4.7979798 ,
        5.05050505,  5.3030303 ,  5.55555556,  5.80808081,  6.06060606,
        6.31313131,  6.56565657,  6.81818182,  7.07070707,  7.32323232,
        7.57575758,  7.82828283,  8.08080808,  8.33333333,  8.58585859,
        8.83838384,  9.09090909,  9.34343434,  9.5959596 ,  9.84848485,
       10.1010101 , 10.35353535, 10.60606061, 10.85858586, 11.11111111,
       11.36363636, 11.61616162, 11.86868687, 12.12121212, 12.37373737,
       12.62626263, 12.87878788, 13.13131313, 13.38383838, 13.63636364,
       13.88888889, 14.14141414, 14.39393939, 14.64646465, 14.8989899 ,
       15.15151515, 15.4040404 , 15.65656566, 15.90909091, 16.16161616,
       16.41414141, 16.66666667, 16.91919192, 17.17171717, 17.42

In [107]:
np.linspace(1,100,10,retstep=True) # retstep- It gives the difference between two consecutive numbers

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

# EYE

In [108]:
# Creates an Identity Matrix

In [109]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random

## Rand

In [111]:
#It will generate random no. from 0 and 1

In [110]:
np.random.rand(4)

array([0.37706552, 0.67617193, 0.6696204 , 0.30710843])

In [112]:
np.random.rand(20)

array([0.10744393, 0.97540336, 0.63037063, 0.69149635, 0.96331359,
       0.34760648, 0.1664461 , 0.66928496, 0.52431848, 0.63912411,
       0.18322039, 0.26191483, 0.14523774, 0.7613728 , 0.56324766,
       0.78002292, 0.49757219, 0.34850166, 0.03069276, 0.67570529])

## randint

In [113]:
# returns random inetger from low(inclusive) to high(exclusive)

In [117]:
np.random.randint(1,100)

15

In [121]:
np.random.randint(1,6)

4

In [122]:
np.random.randint(1,100,10)

array([31, 40, 87, 56, 77, 24, 16, 19, 89, 21])

In [123]:
arr=np.random.randint(0,100,10)

In [124]:
arr

array([42,  3, 79, 26, 42, 81, 60, 27, 86,  5])

In [125]:
arr.mean()

45.1

In [127]:
b=arr.copy()

In [128]:
b

array([42,  3, 79, 26, 42, 81, 60, 27, 86,  5])

In [129]:
arr.cumsum()

array([ 42,  45, 124, 150, 192, 273, 333, 360, 446, 451])

In [130]:
arr.max()

86

In [132]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# Argsort()

In [133]:
a.argsort()

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [134]:
arr.argmax()

8

In [135]:
arr.min()

3

In [136]:
arr.argmin()

1